name: Java CICD with Gradle

on:
  pull_request:
    branches:
      - 'develop'
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: MISO Back CI Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          title: ✅ MISO-Back-CI 성공! ✅
          webhook: ${{ secrets.MISO_DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          image: ${{ secrets.SUCCESS_IMAGE }}
          description: Happy, happy, HAPPY!
          color: 00FF00
          url: "https://github.com/sarisia/actions-status-discord"
          username: MISO CI 봇

      - name: MISO Back CI Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          title: ❗ MISO-Back-CI 실패! ❗️
          webhook: ${{ secrets.MISO_DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          image: ${{ secrets.FAILED_IMAGE }}
          description: Despair
          color: 00FF00
          url: "https://github.com/sarisia/actions-status-discord"
          username: MISO CI 봇